export class Empresa {
  NUMERO_RUC: string;
  RAZON_SOCIAL: string;
  NOMBRE_COMERCIAL?: any;
  ESTADO_CONTRIBUYENTE: string;
  CLASE_CONTRIBUYENTE: string;
  FECHA_INICIO_ACTIVIDADES: string;
  FECHA_ACTUALIZACION: string;
  FECHA_SUSPENSION_DEFINITIVA: string;
  FECHA_REINICIO_ACTIVIDADES?: any;
  OBLIGADO: string;
  TIPO_CONTRIBUYENTE: string;
  NUMERO_ESTABLECIMIENTO: number;
  NOMBRE_FANTASIA_COMERCIAL?: any;
  CALLE: string;
  NUMERO: string;
  INTERSECCION?: any;
  ESTADO_ESTABLECIMIENTO: string;
  DESCRIPCION_PROVINCIA: string;
  DESCRIPCION_CANTON: string;
  DESCRIPCION_PARROQUIA: string;
  CODIGO_CIIU: string;
  ACTIVIDAD_ECONOMICA: string;
}